# Show the dimension player's current dimension
Show dimension: true
# Show the exact coordinates of the player
Show location: true

# The following are Minecraft colour codes from https://www.digminecraft.com/lists/color_list_pc.php
Colour for The Overworld: ยงa
Colour for The Nether: ยง4
Colour for The End: ยง5
